export const USER_SIGNUP_REQ = "USER_SIGNUP_REQ";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_ERROR = "USER_SIGNUP_ERROR"



export const USER_LOGIN_REQ = "USER_LOGIN_REQ";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

export const POST_DATA_REQ = "POST_DATA_REQ";
export const POST_DATA_SUCCESS ="POST_DATA_SUCCESS";
export const POST_DATA_ERROR = "POST_DATA_ERROR";